name: Functions

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        function: [listSlots, updateSlotStatus, startParking, finishParking]

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js v10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Change directory
      run: cd amplify/backend/function/${{ matrix.function }}; pwd
    - name: PWD
      run: pwd
