name: React Application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js v10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install
      run: npm install; echo "export default {};" > src/aws-exports.js
    - name: Build
      run: npm run build
    - name: Test
      run: npm test -- --forceExit --watchAll=false
